AWSTemplateFormatVersion: 2010-09-09
Description: ls3.io Architecture

Parameters:

  Domain:
    Description: The subdomain of this site. (lowercase, dots and dashes please)
    Type: String
    AllowedPattern: '^[a-z0-9-.]*$'

  AcmCert:
    Description: The pre-provisioned ACM Certificate for this site.
    Type: String

  PriceClass:
    Description: '100 < 200 < ALL'
    Type: String
    Default: 100
    AllowedValues:
      - ALL
      - 100
      - 200

Resources:

  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref Domain
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - '/'
              - - !GetAtt Bucket.Arn
                - '*'

  Site:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
      - BucketPolicy
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/404.html'
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: !Sub "PricaeClass_${PriceClass}"
        DefaultCacheBehavior:
          TargetOriginId: !Join
            - '-'
            - - 'S3'
              - !Ref Domain
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 30
          MinTTL: 0
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt Bucket.WebsiteURL]]
            Id: !Join
              - '-'
              - - 'S3'
                - !Ref Domain
            CustomOriginConfig:
              OriginProtocolPolicy: 'http-only'
        ViewerCertificate:
          AcmCertificateArn: !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${AcmCert}'
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
